Teil 5 - Entity Framework Core/dotnetconsulting.TimeTracking/dotnetconsulting.TimeTracking.GuiRazorPages/Pages/TimeTrackingEntries/Edit.cshtml.cs
// Disclaimer
// Dieser Quellcode ist als Vorlage oder als Ideengeber gedacht. Er kann frei und ohne 
// Auflagen oder Einschränkungen verwendet oder verändert werden.
// Jedoch wird keine Garantie übernommen, dass eine Funktionsfähigkeit mit aktuellen und 
// zukünftigen API-Versionen besteht. Der Autor übernimmt daher keine direkte oder indirekte 
// Verantwortung, wenn dieser Code gar nicht oder nur fehlerhaft ausgeführt wird.
// Für Anregungen und Fragen stehe ich jedoch gerne zur Verfügung.

// Thorsten Kansy, www.dotnetconsulting.eu

using AutoMapper;
using dotnetconsulting.TimeTracking.Interfaces;
using dotnetconsulting.TimeTracking.Interfaces.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace dotnetconsulting.TimeTracking.GuiRazorPages.Pages.TimeTrackingEntries
{
    public class EditModel : PageModel, IValidatableObject
    {
        private readonly IAppLogic _appLogic;
        private readonly IMapper _mapper;

        public EditModel(IAppLogic AppLogic, IMapper Mapper)
        {
            _appLogic = AppLogic;
            _mapper = Mapper;
        }

        #region ViewModel
        [HiddenInput]
        [BindProperty]
        public int Id { get; set; }

        public bool IsNewEntry => OrderId == null;

        public IEnumerable<SelectListItem> Orders { get; set; } = null!;

        [Display(Name = "Auftrag")]
        [Required]
        [BindProperty]
        public int? OrderId { get; set; }

        [Display(Name = "Start")]
        [DataType(DataType.Time)]
        [Required]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}", ApplyFormatInEditMode = true)]
        [BindProperty]
        public TimeSpan? Start { get; set; }

        [Display(Name = "Ende")]
        [DataType(DataType.Time)]
        [Required]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}", ApplyFormatInEditMode = true)]
        [BindProperty]
        public TimeSpan? End { get; set; }

        [Display(Name = "Pause")]
        [DataType(DataType.Duration)]
        [Required]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}")]
        [BindProperty]
        public TimeSpan? Break { get; set; }

        [Display(Name = "Buchung am")]
        [DataType(DataType.Date)]
        [Required]
        [BindProperty]
        public DateTime Day { get; set; }

        [Display(Name = "Ort")]
        [Required, MaxLength(50)]
        [BindProperty]
        public string Place { get; set; } = null!;

        [Display(Name = "Beschreibung")]
        [Required]
        [MaxLength(250)]
        [BindProperty]
        public string Description { get; set; } = null!;

        public IEnumerable<ValidationResult> Validate(System.ComponentModel.DataAnnotations.ValidationContext validationContext)
        {
            if (Start > End)
                yield return new ValidationResult("Start muss vor Ende liegen.", new string[] { nameof(Start), nameof(End) });

            if ((End - Start - Break)!.Value.TotalMinutes < 5)
                yield return new ValidationResult("Dauer muss mindestens 5 Minuten betragen.", Array.Empty<string>());
        }
        #endregion

        public async Task OnGetAsync(int Id, CancellationToken cancellationToken)
        {
            EntryDto trackingEntry = await _appLogic.GetTimeTrackingEntryAsync(Id, cancellationToken);
            IList<OrderDto> listOrder = await _appLogic.GetOrdersAsync(cancellationToken);

            // ViewModel erzeugen
            _mapper.Map(trackingEntry, this);
            Orders = _mapper.Map<IEnumerable<SelectListItem>>(listOrder);

            // Fertig
            return;
        }

        public async Task OnGetCreateAsync(CancellationToken cancellationToken)
        {
            EntryDto trackingEntry = await _appLogic.CreateNewTrackingEntryAsync(cancellationToken);
            IList<OrderDto> listOrder = await _appLogic.GetOrdersAsync(cancellationToken);

            // ViewModel erzeugen
            _mapper.Map(trackingEntry, this);
            Orders = _mapper.Map<IEnumerable<SelectListItem>>(listOrder);

            // Das Dto kennt kein null, daher werden die 
            // Werte hier per Code gesetzt
            OrderId = null;
            Start = null;
            End = null;
            Break = null;

            // Fertig
            return;
        }

        public async Task<IActionResult> OnPostAsync(CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                EntryDto entryDto = new();
                _mapper.Map(this, entryDto);
                await _appLogic.StoreTimeTrackingAsync(entryDto, cancellationToken);

                return RedirectToPage("Index");
            }
            else
            {
                // Inhalt des Unter-ViewModel wird nicht gepostet
                var listOrder = await _appLogic.GetOrdersAsync(cancellationToken);
                Orders = _mapper.Map<IEnumerable<SelectListItem>>(listOrder);

                return null!;
            }
        }
    }
}

Teil 5 - Entity Framework Core/dotnetconsulting.TimeTracking/dotnetconsulting.TimeTracking.GuiRazorPages/Pages/TimeTrackingEntries/Index.cshtml.cs
// Disclaimer
// Dieser Quellcode ist als Vorlage oder als Ideengeber gedacht. Er kann frei und ohne 
// Auflagen oder Einschränkungen verwendet oder verändert werden.
// Jedoch wird keine Garantie übernommen, dass eine Funktionsfähigkeit mit aktuellen und 
// zukünftigen API-Versionen besteht. Der Autor übernimmt daher keine direkte oder indirekte 
// Verantwortung, wenn dieser Code gar nicht oder nur fehlerhaft ausgeführt wird.
// Für Anregungen und Fragen stehe ich jedoch gerne zur Verfügung.

// Thorsten Kansy, www.dotnetconsulting.eu

using AutoMapper;
using dotnetconsulting.TimeTracking.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace dotnetconsulting.TimeTracking.GuiRazorPages.Pages.TimeTrackingEntries;

public class IndexModel : PageModel
{
    private readonly IAppLogic _appLogic;
    private readonly IMapper _mapper;

    public IndexModel(IAppLogic AppLogic, IMapper Mapper)
    {
        _appLogic = AppLogic;
        _mapper = Mapper;
    }

    #region ViewModel
    public IEnumerable<TimeTrackingEntryViewModel> List { get; set; } = null!;

    public IEnumerable<SelectListItem> Orders { get; set; } = null!;

    [Display(Name = "Auftrag")]
    public int? OrderId { get; set; }

    [Display(Name = "Von")]
    [DataType(DataType.Date)]
    [DisplayFormat(ConvertEmptyStringToNull = true)]
    public DateTime? FilterStart { get; set; }

    [Display(Name = "Bis")]
    [DataType(DataType.Date)]
    [DisplayFormat(ConvertEmptyStringToNull = true)]
    public DateTime? FilterEnd { get; set; }

    public class TimeTrackingEntryViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Auftrag")]
        public string CustomerAndOrder { get; set; } = null!;

        [Display(Name = "Start")]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}", ApplyFormatInEditMode = true)]
        public TimeSpan Start { get; set; }

        [Display(Name = "Ende")]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}", ApplyFormatInEditMode = true)]
        public TimeSpan End { get; set; }

        [Display(Name = "Pause")]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}")]
        public TimeSpan Break { get; set; }

        [Display(Name = "Dauer")]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}")]
        public TimeSpan Duration => (End - Start - Break);

        [Display(Name = "Buchung am")]
        [DataType(DataType.Date)]
        public DateTime Day { get; set; }

        [Display(Name = "Ort")]
        public string Place { get; set; } = null!;

        [Display(Name = "Beschreibung")]
        public string Description { get; set; } = null!;
    }
    #endregion

    public async Task OnGetAsync([FromQuery(Name = "s")] DateTime? Start, [FromQuery(Name = "e")] DateTime? End, [FromQuery(Name = "order")] int? OrderId, CancellationToken cancellationToken)
    {
        // Daten abfragen
        var listData = await _appLogic.GetTimeTrackingEntriesAsync(Start, End, OrderId, cancellationToken);
        var listOrder = await _appLogic.GetOrdersAsync(cancellationToken);

        // ViewModel erzeugen
        List = _mapper.Map<IEnumerable<TimeTrackingEntryViewModel>>(listData);
        Orders = _mapper.Map<IEnumerable<SelectListItem>>(listOrder);

        FilterStart = Start;
        FilterEnd = End;
        this.OrderId = OrderId;

        // Fertig
        return;
    }

    public async Task<IActionResult> OnGetDeleteAsync(int id, CancellationToken cancellationToken)
    {
        await _appLogic.DeleteTimeTrackingAsync(id, cancellationToken);

        return RedirectToPage();
    }
}

Teil 5 - Entity Framework Core/dotnetconsulting.TimeTracking/dotnetconsulting.TimeTracking.GuiRazorPages/Pages/TimeTrackingEntries/Edit.cshtml
@page
@model dotnetconsulting.TimeTracking.GuiRazorPages.Pages.TimeTrackingEntries.EditModel

@if (Model.IsNewEntry)
{
    <h2>Eintrag hinzufügen</h2>
}
else
{
    <h2>Eintrag bearbeiten</h2>
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <input asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label><br />
                <select asp-for="OrderId" asp-items="@Model.Orders" class="form-control">
                    @if (Model.IsNewEntry)
                    {
                        <option value="">(Bitte wählen)</option>
                    }
                </select>
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Break" class="control-label"></label>
                <input asp-for="Break" class="form-control" />
                <span asp-validation-for="Break" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Speichern" class="btn btn-default" />
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Zurück zur Übersicht</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Teil 5 - Entity Framework Core/dotnetconsulting.TimeTracking/dotnetconsulting.TimeTracking.GuiRazorPages/Pages/TimeTrackingEntries/Index.cshtml
@page
@model dotnetconsulting.TimeTracking.GuiRazorPages.Pages.TimeTrackingEntries.IndexModel

@{ TimeSpan durationSum = new TimeSpan(); }

<h2>Gebuchte Zeiten</h2>
<style>
    .doubleunderline {
        text-decoration: double;
        border-bottom: 1px solid #000;
    }
</style>
<p>
    <a asp-page="Edit" asp-page-handler="create">Neuen Eintrag anlegen</a>
</p>
<form>
    <div class="form-group">
        <label asp-for="FilterStart" class="col-md-1 control-label"></label>
        <div class="col-md-2">
            <input asp-for="FilterStart" name="s" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="FilterEnd" class="col-md-1 control-label"></label>
        <div class="col-md-2">
            <input asp-for="FilterEnd" name="e" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="OrderId" class="col-md-1 control-label"></label>
        <div class="col-md-2">
            <select asp-for="OrderId" asp-items="@Model.Orders" name="order">
                <option value="">(Alle)</option>
            </select>
        </div>
    </div>
    <button>Anwenden</button>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <label asp-for="List.First().Day"></label>
                </th>
                <th>
                    <label asp-for="List.First().CustomerAndOrder"></label>
                </th>
                <th>
                    <label asp-for="List.First().Start"></label>
                </th>
                <th>
                    <label asp-for="List.First().End"></label>
                </th>
                <th>
                    <label asp-for="List.First().Break"></label>
                </th>
                <th>
                    <label asp-for="List.First().Duration"></label>
                </th>
                <th>
                    <label asp-for="List.First().Place"></label>
                </th>
                <th>
                    <label asp-for="List.First().Description"></label>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.List)
            {
                // Dauer der Buchungen aufsummieren
                durationSum += item.Duration;

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Day)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerAndOrder)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Start)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.End)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Break)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Place)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <a asp-page="Edit" asp-route-id="@item.Id">Bearbeiten</a>
                        <a asp-route-id="@item.Id" asp-page-handler="delete" onclick="return confirm('Buchung löschen?');">Löschen</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
                <td>
                    <label class="doubleunderline">@durationSum.ToString(@"hh\:mm")</label>
                </td>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
            </tr>
        </tfoot>
    </table>
</form>